### ISSUE TITLE
ViewInjector only generates method from the first interface super class

### ISSUE THREAD

**Issue by CarlosMChica** [PaNaVTEC/ViewThreadDecorator#4]

**Comment by CarlosMChica** [comment]
It does work if the annotated @ThreadViewDecorated interface es de highest interface in the hierarchy

**Comment by CarlosMChica** [comment]
if an interface extends more than one interface then the generated decorated class should implement all interfaces.

**Comment by PaNaVTEC** [comment]
So, for readers, the problem is if you have a view interface hierarchy with more than 2 parents. It will be fixed in the next release.

**Comment by PaNaVTEC** [comment]
Fixed in 1.5.2
